default: true
MD001: false
MD003: 
  style: atx
MD004: 
  style: dash
MD006: false
MD007: 
  indent: 2
MD013: false
MD018: false
MD026:
  punctuation: ',;:'
MD033: false
MD035:
  style: ---
MD036: false
MD041: false
MD048: 
  style: backtick
