default: true
MD001: false
MD002: false
MD004: 
  style: dash
MD006: false
MD007: 
  indent: 2
MD013: 
  line_length: 1000
MD018: false
MD024: false
MD026: false
MD033: false
MD036: false
MD041: false
MD048: 
  style: backtick
